### ISSUE TITLE
Zotero 5?

### ISSUE THREAD

**Issue by bwiernik** [fractaledmind/alfred_zotquery#9]
Are you planning to update the workflow to support Zotero 5?

**Comment by fractaledmind** [comment]
I am no longer in the academy and thus no longer use Zotero regularly. Sadly, as a result, I no longer use this workflow and have no plans on updating it.

However, if you or someone else or even a group of people wanted to take control of the workflow, I would be happy to walk them thru the codebase as it is now and hand over the codebase for further development.

**Comment by bwiernik** [comment]
Hi, okay, thanks for the information. I don't use Alfred, so I'm not particuarly motivated to work on it, but I'll update the listing on the Zotero plugins page. Thanks.

**Comment by Damianeire** [comment]
@fractaledmind Firstly, thanks for all your work in getting it this far, it was very very useful for many people. I'm sorry you're no longer in the academy (unless you didn't want to be there of course, in which case, congratulations!). I took the liberty of linking this conversation over on the Alfred zotquery page as there is someone there (lutefish) who is at least interested in looking at the workflow (and has already). I couldn't say for sure whether he will be in touch, but I thought I'd mention it. Thanks again Stephen.

**Comment by lutefiasco** [comment]
@fractaledmind I'll join the chorus of thanks. I've forked your GitHub repository, and uploaded a few duct-tape-and-bailing-wire hacks to the repository there. I have a currently working version (of Alfred 3 and Zotero 5), but I don't know if anyone else has been able to get my ugly version working. I'm at the outer limits of my technical abilities, so I'm not sure it's worth your time to walk me through the codebase. Best of luck with your current and future endeavors, regardless, and thanks for making such a useful tool for Alfred-using academics.

**Comment by bwiernik** [comment]
@lutefiasco I'll add a link to your fork on the Zotero plugins page, with a note that the 5.0-compatible version is in an alpha stage.

**Comment by deanishe** [comment]
> I'm at the outer limits of my technical abilities

Pfft. That never stopped @fractaledmind.

If there's anything you think I can help you with, I'll do what I can.
